# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

Character.create(name: 'President Morty', description: 'President Morty, colloquially known as Evil Morty, Eye Patch Morty, or as Candidate Morty prior to his election, is the secondary antagonist of Rick and Morty. He serves as the secondary antagonist and the bigger bad of Close Rick-Counters of the Rick Kind, the main antagonist of Tales from the Citadel and a cameo antagonist in Never Ricking Morty.', category: 'Morty', photo_url: 'Evil_Morty_NeverRicking_Morty', availability: true)
Character.create(name: 'Morty Smith', description: 'Mortimer "Morty" Smith Sr. is one of the two titular main protagonists of Rick and Morty.', category: 'Morty', photo_url: 'Morty_Smith', availability: true)
Character.create(name: 'Morticia', description: 'Morticia is a gender-swapped version of Morty Smith in Pocket Mortys and the 111th Morty in the Morty Deck. She was the only female Morty in the game before Girl Morty was added.', category: 'Morty', photo_url: 'Morticia', availability: true)
Character.create(name: 'The One True Morty', description: 'The One True Morty is a version of Morty Smith in Pocket Mortys and the 82nd Morty in the Morty Deck. It can only be aquired by evolving Egg Morty to level 20.', category: 'Morty', photo_url: 'The_one_true_morty', availability: true)
Character.create(name: 'Egg Morty', description: 'Egg Morty is a character from Pocket Mortys. This Morty is obtained from Masy Kallerax s quest, New Chef in the Rickchen. It evolves into the One True Morty once it reaches Level 20.', category: 'Morty', photo_url: 'Egg_morty', availability: true)
Character.create(name: 'Ace Pilot Morty', description: 'This ol Morty can t be beat in the skys. Even when drawing crabs this old chap can be seen zigzagging around every archie and never pipped, not even once what what!', category: 'Morty', photo_url: 'Ace_pilot_morty', availability: true)
Character.create(name: 'Elf Morty', description: 'This Morty works at the North Poll along with thousands of other enslaved Elf Mortys working on their Rick s secret holiday device', category: 'Morty', photo_url: 'Elf_morty', availability: true)
Character.create(name: 'Alien Morty', description: 'Alien Morty is an alternate version of Morty Smith who appeared in the episode Close Rick-Counters of the Rick Kind.', category: 'Morty', photo_url: 'Alien_morty', availability: true)

Character.create(name: 'Rick Sanchez', description: 'Rick D. Sanchez, also known as Rick C-137, is one of the two titular main protagonists as well as the main antagonist of Rick and Morty.', category: 'Rick', photo_url: 'Rick_Sanchez' , availability: true)
Character.create(name: 'Doofus Rick', description: 'What s that dipshit doing out there? Are you FRIENDS with him?! You know he eats his own shit, right?', category: 'Rick', photo_url: 'Doofus_rick', availability: true)
Character.create(name: 'Council of Ricks', description: 'The Council of Ricks was the governing body over all Ricks who joined them. The Council was created when Ricks from multiple dimensions decided to form a way for Ricks to protect one another from their enemies across realities and ruled from their secret headquarters known as The Citadel.', category: 'Rick', photo_url: 'Council_of_ricks', availability: true)
Character.create(name: 'Pickle Rick', description: 'Pickle Rick is a version of Rick Sanchez first seen in a teaser for Season 3 of Rick and Morty. He appears in the episode of the same name and makes a cameo appearance in Edge of Tomorty: Rick Die Rickpeat in a death crystal vision.', category: 'Rick', photo_url: 'Pickle_rick', availability: true)
Character.create(name: 'Evil Rick Sanchez', description: 'We both know if there s a truth in the universe: it s that Ricks don t care about Mortys.', category: 'Rick', photo_url: 'Evil_rick_sanchez', availability: true)
Character.create(name: 'Tiny Rick', description: 'Tiny Rick is a younger version of Rick created through Operation Phoenix in the episode Big Trouble In Little Sanchez. By transferring his consciousness into the brain of a younger clone, Rick is able to attend Harry Herpson High School, along with Morty and Summer, in an effort to help catch a vampire within their school.', category: 'Rick', photo_url: 'Tiny_rick', availability: true)
Character.create(name: 'Rick (Fortnite)', description: 'The Rickest Rick of them all. Misanthropic scientist and self-proclaimed smartest man in the multiverse.', category: 'Rick', photo_url: 'Rick_fortnite', availability: true)
Character.create(name: 'Adjudicator Rick', description: 'The number of displaced Mortys is soaring, while Rick satisfaction levels are plummeting, and the divide between the two groups has never been wider. Solve that one real quick.', category: 'Rick', photo_url: 'Adjudicator_rick', availability: true)
